/****************************************Copyright (c)**********************************************
**                                   成都运达科技股份公司
* 文件名        : Port_Cfg.c
* 功能描述      : Port模块配置头文件(.h)定义
*
*            +----- (NEW | MODify | ADD | DELete)
*            |
* 版本       |    日期         姓名             版本描述
*----------+---+------------+------------------+----------------------------------------------------
* 1.0.0       2017/4/25       chenms             NEW
**------------------------------------------------------------------------------------------------*/

/**************************** 引用部分 *********************************/
#include "Port_Cfg.h"
#include "Port_CfgType.h"
#include "Port_Define.h"
#include "drv_pio.h"  /*add by chenms 2017-10-27*/
/**************************** 定义部分 *********************************/
/************************************
          主控板引脚定义
************************************/
const Port_PinConfigurationType Port_PinConfig[49]=
{
	/*状态指示灯 LED1~5*/
	{PORT_PIN_PAD1 , PORT_PAD, DRV_PIO_PAD1, PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT, FALSE, PORT_PIN_LEVEL_LOW},/*运行灯*/
	{PORT_PIN_PAD2 , PORT_PAD, DRV_PIO_PAD2, PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT, FALSE, PORT_PIN_LEVEL_LOW},/*工作模式*/
	{PORT_PIN_PAD3 , PORT_PAD, DRV_PIO_PAD3, PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT, FALSE, PORT_PIN_LEVEL_LOW},/*DC24V电源*/
	{PORT_PIN_PAD4 , PORT_PAD, DRV_PIO_PAD4, PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT, FALSE, PORT_PIN_LEVEL_LOW},/*DC12V电源*/
	{PORT_PIN_PAD5 , PORT_PAD, DRV_PIO_PAD5, PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT, FALSE, PORT_PIN_LEVEL_LOW},/*DC5V电源*/

	/*状态指示灯 LED6~10*/
	{PORT_PIN_PAD6 , PORT_PAD, DRV_PIO_PAD6, PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT, FALSE, PORT_PIN_LEVEL_LOW},/*CAN1通讯*/
	{PORT_PIN_PAD7 , PORT_PAD, DRV_PIO_PAD7, PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT, FALSE, PORT_PIN_LEVEL_LOW},/*CAN2通讯*/
	{PORT_PIN_PAD8 , PORT_PAD, DRV_PIO_PAD8, PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT, FALSE, PORT_PIN_LEVEL_LOW},/*以太网通讯*/
	{PORT_PIN_PAD9 , PORT_PAD, DRV_PIO_PAD9, PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT, FALSE, PORT_PIN_LEVEL_LOW },/*入库/出库*/
	{PORT_PIN_PAD10, PORT_PAD, DRV_PIO_PAD10,PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT, FALSE, PORT_PIN_LEVEL_LOW },/*水位报警*/
	
	/*状态指示灯 LED11~15*/
	{PORT_PIN_PAD11, PORT_PAD,DRV_PIO_PAD11 ,PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT, FALSE, PORT_PIN_LEVEL_LOW },/*线阵触发*/
	{PORT_PIN_PAD12, PORT_PAD,DRV_PIO_PAD12 ,PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT, FALSE, PORT_PIN_LEVEL_LOW },/*面阵触发*/
	{PORT_PIN_PAD13, PORT_PAD,DRV_PIO_PAD13 ,PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT, FALSE, PORT_PIN_LEVEL_LOW },/*沉箱开/关门*/
	{PORT_PIN_PAD14, PORT_PAD,DRV_PIO_PAD14 ,PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT, FALSE, PORT_PIN_LEVEL_LOW},/*ZXB侧箱开/关门*/
	{PORT_PIN_PAD15, PORT_PAD,DRV_PIO_PAD15 ,PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT, FALSE, PORT_PIN_LEVEL_LOW},/*CT侧箱开/关门*/

	/*状态指示灯 LED16~20*/
	{PORT_PIN_PAD16, PORT_PAD,DRV_PIO_PAD16,PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT, FALSE, PORT_PIN_LEVEL_LOW},/*闸瓦开/关门*/
	{PORT_PIN_PP0  , PORT_P ,  DRV_PIO_PP0, PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT, FALSE, PORT_PIN_LEVEL_LOW },/*闸片开/关门*/
	{PORT_PIN_PP1  , PORT_P ,  DRV_PIO_PP1, PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT, FALSE, PORT_PIN_LEVEL_LOW },/*齿轮箱开/关门*/
	{PORT_PIN_PP2  , PORT_P ,  DRV_PIO_PP2, PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT, FALSE, PORT_PIN_LEVEL_LOW },/*除尘开/关*/
	{PORT_PIN_PP3  , PORT_P ,  DRV_PIO_PP3, PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT, FALSE, PORT_PIN_LEVEL_LOW },/*散热开/关*/
	
	/*状态指示灯 LED21~25*/
	{PORT_PIN_PP4,  PORT_P,  DRV_PIO_PP4, PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT, FALSE, PORT_PIN_LEVEL_LOW },/*加热开/关*/
	{PORT_PIN_PP5,  PORT_P,  DRV_PIO_PP5, PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT, FALSE, PORT_PIN_LEVEL_LOW },/*公共信号板*/
	{PORT_PIN_PP6,  PORT_P,  DRV_PIO_PP6, PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT, FALSE, PORT_PIN_LEVEL_LOW },/*沉箱控制板*/
	{PORT_PIN_PP7,  PORT_P,  DRV_PIO_PP7, PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT, FALSE, PORT_PIN_LEVEL_LOW },/*侧箱控制板*/
	{PORT_PIN_PH2,  PORT_H,  DRV_PIO_PH2, PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT, FALSE, PORT_PIN_LEVEL_LOW },/*车顶控制板*/
	
	/*状态指示灯 LED26~30*/
	{PORT_PIN_PH3,  PORT_H,  DRV_PIO_PH3, PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT, FALSE, PORT_PIN_LEVEL_LOW },/*面阵控制板1*/
	{PORT_PIN_PH4,  PORT_H,  DRV_PIO_PH4, PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT, FALSE, PORT_PIN_LEVEL_LOW },/*面阵控制板2*/
	{PORT_PIN_PH5,  PORT_H,  DRV_PIO_PH5, PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT, FALSE, PORT_PIN_LEVEL_LOW },/*预留*/
	{PORT_PIN_PH6,  PORT_H,  DRV_PIO_PH6, PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT, FALSE, PORT_PIN_LEVEL_LOW },/*预留*/
	{PORT_PIN_PH7,  PORT_H,  DRV_PIO_PH7, PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT, FALSE, PORT_PIN_LEVEL_LOW },/*预留*/

	/*按键指示灯 LED1~5*/
	{PORT_PIN_PA1,  PORT_A,  DRV_PIO_PA1,  PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT ,FALSE, PORT_PIN_LEVEL_LOW },/*LED1*/
	{PORT_PIN_PK0,  PORT_K,  DRV_PIO_PK0,  PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT ,FALSE, PORT_PIN_LEVEL_LOW },/*LED2*/
	{PORT_PIN_PK1,  PORT_K,  DRV_PIO_PK1,  PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT ,FALSE, PORT_PIN_LEVEL_LOW },/*LED3*/		
	{PORT_PIN_PK2,  PORT_K,  DRV_PIO_PK2,  PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT ,FALSE, PORT_PIN_LEVEL_LOW },/*LED4*/
	{PORT_PIN_PK3,  PORT_K,  DRV_PIO_PK3,  PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT ,FALSE, PORT_PIN_LEVEL_LOW },/*LED5*/
	
	/*按键指示灯 LED6~9*/
	{PORT_PIN_PK4,  PORT_K,  DRV_PIO_PK4,  PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT ,FALSE, PORT_PIN_LEVEL_LOW },/*LED6*/
	{PORT_PIN_PK5,  PORT_K,  DRV_PIO_PK5,  PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT ,FALSE, PORT_PIN_LEVEL_LOW },/*LED7*/
	{PORT_PIN_PK6,  PORT_K,  DRV_PIO_PK6,  PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT ,FALSE, PORT_PIN_LEVEL_LOW },/*LED8*/
	{PORT_PIN_PK7,  PORT_K,  DRV_PIO_PK7,  PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT ,FALSE, PORT_PIN_LEVEL_LOW },/*LED9*/

	/*按键 KEY1~5*/
	{PORT_PIN_PT0,  PORT_T,  DRV_PIO_PT0, PORT_PIN_MODE_DIO, FALSE, PORT_PIN_IN, FALSE, PORT_PIN_LEVEL_LOW},/*运行/维护*/
	{PORT_PIN_PT1,  PORT_T,  DRV_PIO_PT1, PORT_PIN_MODE_DIO, FALSE, PORT_PIN_IN, FALSE, PORT_PIN_LEVEL_LOW},/*本地/远方*/
	{PORT_PIN_PT2,  PORT_T,  DRV_PIO_PT2, PORT_PIN_MODE_DIO, FALSE, PORT_PIN_IN, FALSE, PORT_PIN_LEVEL_LOW},/*开门/关门*/
	{PORT_PIN_PT3,  PORT_T,  DRV_PIO_PT3, PORT_PIN_MODE_DIO, FALSE, PORT_PIN_IN, FALSE, PORT_PIN_LEVEL_LOW},/*除尘开/关*/
	{PORT_PIN_PT4,  PORT_T,  DRV_PIO_PT4, PORT_PIN_MODE_DIO, FALSE, PORT_PIN_IN, FALSE, PORT_PIN_LEVEL_LOW},/*散热开/关*/

	/*按键 KEY6~9*/
	{PORT_PIN_PT5,  PORT_T,  DRV_PIO_PT5, PORT_PIN_MODE_DIO, FALSE, PORT_PIN_IN, FALSE, PORT_PIN_LEVEL_LOW},/*加热开/关*/
	{PORT_PIN_PT6,  PORT_T,  DRV_PIO_PT6, PORT_PIN_MODE_DIO, FALSE, PORT_PIN_IN, FALSE, PORT_PIN_LEVEL_LOW},/*线阵开/关*/
	{PORT_PIN_PT7,  PORT_T,  DRV_PIO_PT7, PORT_PIN_MODE_DIO, FALSE, PORT_PIN_IN, FALSE, PORT_PIN_LEVEL_LOW},/*面阵开/关*/
	{PORT_PIN_PAD0, PORT_PAD,DRV_PIO_PAD0,PORT_PIN_MODE_DIO, FALSE, PORT_PIN_IN, FALSE, PORT_PIN_LEVEL_LOW},/*模拟开/关*/

    /*看门狗喂狗线*/
	{PORT_PIN_PH0  ,PORT_H,  DRV_PIO_PH0,  PORT_PIN_MODE_DIO, FALSE, PORT_PIN_OUT,FALSE, PORT_PIN_LEVEL_LOW },/*WDI*/
};  

const Port_ConfigType  Port_Config=
{
    49u,
    &Port_PinConfig[0]
};



